/* build-intake.js — generate the form-only customer intake page.
   ─────────────────────────────────────────────────────────────────────────
   The public /intake page must NOT ship the confidential Source-Map data
   (data.js / fields-data.js). So instead of serving the full app, we extract
   ONLY the intake form's CSS + JS from index.html and inline intake-data.js
   into a single self-contained file.

   Outputs:
     public/intake.html        — served at /intake by the web app
     ../Intake_Form_POC.html    — the emailable/standalone copy (kept in sync)

   Run:  node build-intake.js   (or  npm run build:intake)
   Re-run after editing the intake form in index.html or intake-data.js.
*/
'use strict';

const fs = require('fs');
const path = require('path');

const here = __dirname;
const html = fs.readFileSync(path.join(here, 'index.html'), 'utf8');
const intakeData = fs.readFileSync(path.join(here, 'intake-data.js'), 'utf8');
const validationJs = fs.readFileSync(path.join(here, 'validation.js'), 'utf8');
const flagsJs = fs.readFileSync(path.join(here, 'flags.js'), 'utf8');

function must(re, label) {
  const m = html.match(re);
  if (!m) throw new Error('build-intake: could not locate ' + label);
  return m[0];
}

// ── CSS pieces ──
const rootCss = must(/:root \{[\s\S]*?\n\}/, ':root tokens');
const resetCss = must(/\*, \*::before[\s\S]*?\nbody \{[\s\S]*?\}/, 'reset + body');
const toastCss = must(/\.fe-toast \{[\s\S]*?\.fe-toast\.show \{[^}]*\}/, '.fe-toast rules');
const inCss = must(/\/\* ─── IntakeForm\.jsx[\s\S]*?(?=\/\* ─── IntakeReview\.jsx)/, 'IntakeForm CSS block');

// ── JS pieces ──
const toastJs = must(/let feToastTimer;[\s\S]*?feToastTimer = setTimeout[\s\S]*?\n\}/, 'feToast()');
const irLabel = must(/function irFieldLabel\(k\) \{[\s\S]*?\n\}/, 'irFieldLabel()');

// The whole intake VIEW block (inInit … inReviewSectionHTML), located by the
// JS banner comments (the "(views/…jsx)" markers are unique to the script,
// so this survives line shifts and ignores the HTML <!-- --> comments).
const startIdx = html.lastIndexOf('/*', html.indexOf('(views/IntakeForm.jsx)'));
const endIdx = html.lastIndexOf('/*', html.indexOf('(views/IntakeReview.jsx)'));
if (startIdx < 0 || endIdx < 0 || endIdx <= startIdx) throw new Error('build-intake: could not locate intake JS block');
const intakeBlk = html.slice(startIdx, endIdx);

const out = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Sojo Industries — New Project Intake</title>
<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@500;700&display=swap" rel="stylesheet"/>
<style>
/* ═══ Auto-generated by build-intake.js — do not edit by hand.
   Source of truth: blueprint-app/index.html + intake-data.js.
   Self-contained customer intake form (no Source-Map data shipped). ═══ */
${rootCss}

${resetCss}

${toastCss}

${inCss}

/* standalone: the form IS the page */
.in-stage { min-height: 100vh; }
</style>
</head>
<body>
<div class="in-stage" id="intakeView"></div>

<script>
/* Inlined from intake-data.js */
${intakeData}
</script>

<script>
/* Inlined from validation.js + flags.js (gating + flag logic) */
${validationJs}
${flagsJs}
</script>

<script>
${toastJs}

${intakeBlk}
${irLabel}

/* ── standalone bootstrap ── */
inInit();
inRender();
</script>
</body>
</html>
`;

fs.mkdirSync(path.join(here, 'public'), { recursive: true });
const publicPath = path.join(here, 'public', 'intake.html');
const sharePath = path.join(here, '..', 'Intake_Form_POC.html');
fs.writeFileSync(publicPath, out, 'utf8');
fs.writeFileSync(sharePath, out, 'utf8');

const kb = (out.length / 1024).toFixed(1);
console.log(`build-intake: wrote ${kb} KB`);
console.log('  → ' + publicPath);
console.log('  → ' + sharePath);
